name: CI Keep White Space

on:
  push:
    branches:
      - '**'          # S'active sur un push sur n'importe quelle branche
  pull_request:
    branches:
      - main          # S'active sur une PR visant la branche principale
  workflow_dispatch:  # Permet le lancement manuel

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Security Audit (npm audit)
        run: npm audit --audit-level=moderate

      - name: Linting (Google Style Guide)
        run: npm run lint

      - name: Run Tests with Annotations
        run: npm test

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Cette étape transforme le pseudo en minuscules pour Docker
      - name: Lowercase repo holder
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # On utilise ici la variable REPO_OWNER qui est maintenant en minuscules
          tags: ghcr.io/${{ env.REPO_OWNER }}/keep-white-space:latest